#!/bin/bash

# =============================================================================
# HCP FreeSurfer pipeline: SLURM array job
# =============================================================================
#
# Purpose
# -------
# Run the HCP FreeSurfer structural-processing stage for multiple subjects using a SLURM job array and the HCP Pipelines Singularity container.
#
# Each array task:
#   1. Reads one subject identifier from subjects_ses01.txt.
#   2. Mounts the project directory inside the container.
#   3. Uses the outputs generated by the preceding PreFreeSurfer stage.
#   4. Runs FreeSurferPipeline.sh for that subject.
#
# Inputs
# ------
# - Subject list:
#     /scratch/users/k20009014/subjects_ses01.txt
# - PreFreeSurfer outputs:
#     /scratch/users/k20009014/derivatives_batch/<subject>/T1w/
# - HCP Pipelines container:
#     /scratch/users/k20009014/hcppipelines_latest.sif
# - FreeSurfer licence:
#     /scratch/users/k20009014/license.txt
#
# Outputs
# -------
# FreeSurfer outputs are written within each subject's T1w directory under:
#     /scratch/users/k20009014/derivatives_batch/
#
# One standard-output log and one error log are produced per array task under:
#     /scratch/users/k20009014/logs/
#
# Notes
# -----
# - The array range 1-12 assumes that the subject list contains 12 entries.
# - The script uses T1-weighted data only; T2-weighted input is set to NONE.
# - The HCP LegacyStyleData processing mode is retained.
# =============================================================================


# -------------------------------------------------------------------------
# SLURM resource requests and logging
# -------------------------------------------------------------------------

#SBATCH --job-name=FS_batch
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=24:00:00
#SBATCH --array=1-12

# %A is the parent SLURM job ID and %a is the array-task ID.
#SBATCH --output=/scratch/users/k20009014/logs/FS_%A_%a.out
#SBATCH --error=/scratch/users/k20009014/logs/FS_%A_%a.err


# -------------------------------------------------------------------------
# Select the subject assigned to the current array task
# -------------------------------------------------------------------------

# Read the line corresponding to SLURM_ARRAY_TASK_ID from the subject list.
SUBJECT=$(sed -n "${SLURM_ARRAY_TASK_ID}p" /scratch/users/k20009014/subjects_ses01.txt)


# -------------------------------------------------------------------------
# Execute the HCP FreeSurfer pipeline inside the container
# -------------------------------------------------------------------------

# Environment variables provide the FreeSurfer licence and HCP Pipelines paths.
# The user's scratch directory is mounted as /work inside the container.
singularity exec \
--env FS_LICENSE=/work/license.txt \
--env HCPPIPEDIR=/work/HCPpipelines_shang/HCPpipelines \
--env HCPPIPEDIR_Global=/work/HCPpipelines_shang/HCPpipelines/global \
--env HCPPIPEDIR_Templates=/work/HCPpipelines_shang/HCPpipelines/global/templates \
--env HCPPIPEDIR_Config=/work/HCPpipelines_shang/HCPpipelines/global/config \
--bind /scratch/users/k20009014:/work \
/scratch/users/k20009014/hcppipelines_latest.sif \
bash -c "

# Exit immediately if a command fails or an undefined variable is used.
set -eu

# Subject identifier passed from the SLURM array task.
Subject=${SUBJECT}

# Root directory containing the HCP derivatives generated by PreFreeSurfer.
StudyFolder=/work/derivatives_batch

# Subject-specific working directory expected by the HCP FreeSurfer pipeline.
SubjectDIR=\${StudyFolder}/\${Subject}/T1w

# T1-weighted anatomical image and brain-extracted image produced by
# PreFreeSurfer and used as inputs to this stage.
T1wImage=\${StudyFolder}/\${Subject}/T1w/T1w_acpc_dc_restore.nii.gz
T1wImageBrain=\${StudyFolder}/\${Subject}/T1w/T1w_acpc_dc_restore_brain.nii.gz

# Print the resolved subject and output directory to the SLURM log.
echo Subject: \${Subject}
echo SubjectDIR: \${SubjectDIR}


# -------------------------------------------------------------------------
# Run FreeSurferPipeline.sh
# -------------------------------------------------------------------------

# This stage performs cortical reconstruction and surface processing using
# the T1-weighted outputs from PreFreeSurfer. No T2-weighted image is supplied.
\${HCPPIPEDIR}/FreeSurfer/FreeSurferPipeline.sh \
  --subject=\${Subject} \
  --subjectDIR=\${SubjectDIR} \
  --t1=\${T1wImage} \
  --t1brain=\${T1wImageBrain} \
  --t2=NONE \
  --processing-mode=LegacyStyleData
"
