#!/bin/bash

# =============================================================================
# HCP PostFreeSurfer pipeline: SLURM array job
# =============================================================================
#
# Purpose
# -------
# Run the HCP PostFreeSurfer stage for multiple subjects using a SLURM job array. 
# This stage converts the FreeSurfer outputs into the HCP surface and grayordinate framework and performs surface registration using MSMSulc.
#
# Each array task:
#   1. Reads one subject identifier from subjects_ses01.txt.
#   2. Starts the container with the required HCP, FSL, Connectome Workbench
#      and MSM paths.
#   3. Uses the outputs generated by the preceding FreeSurfer stage.
#   4. Runs PostFreeSurferPipeline.sh for the selected subject.
#
# Inputs
# ------
# - Subject list:
#     /scratch/users/k20009014/subjects_ses01.txt
# - FreeSurfer outputs:
#     /scratch/users/k20009014/derivatives_batch/<subject>/
# - Container:
#     /scratch/users/k20009014/fmriprep_latest.sif
# - FreeSurfer licence:
#     /scratch/users/k20009014/license.txt
#
# Outputs
# -------
# PostFreeSurfer derivatives are written within:
#     /scratch/users/k20009014/derivatives_batch/
#
# One standard-output log and one error log are written for each array task
# under:
#     /scratch/users/k20009014/logs/
#
# Notes
# -----
# - The array range 1-12 assumes that the subject list contains 12 entries.
# - Surface registration uses MSMSulc.
# - The script creates 164k high-resolution and 32k low-resolution meshes.
# - Grayordinates are generated at 2 mm resolution.
# =============================================================================


# -------------------------------------------------------------------------
# SLURM resource requests and logging
# -------------------------------------------------------------------------

#SBATCH --job-name=PostFS_batch
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --array=1-12

# %A is the parent SLURM job ID and %a is the array-task ID.
#SBATCH --output=/scratch/users/k20009014/logs/PostFS_%A_%a.out
#SBATCH --error=/scratch/users/k20009014/logs/PostFS_%A_%a.err


# -------------------------------------------------------------------------
# Select the subject assigned to the current array task
# -------------------------------------------------------------------------

# Read the line corresponding to SLURM_ARRAY_TASK_ID from the subject list.
SUBJECT=$(sed -n "${SLURM_ARRAY_TASK_ID}p" /scratch/users/k20009014/subjects_ses01.txt)


# -------------------------------------------------------------------------
# Execute the PostFreeSurfer pipeline inside the container
# -------------------------------------------------------------------------

# Environment variables define the FreeSurfer licence, HCP Pipelines, Connectome Workbench, FSL and MSM executable/configuration locations.
# The user's scratch directory is mounted as /work inside the container.
singularity exec \
--env FS_LICENSE=/work/license.txt \
--env HCPPIPEDIR=/work/HCPpipelines_shang/HCPpipelines \
--env HCPPIPEDIR_Global=/work/HCPpipelines_shang/HCPpipelines/global \
--env HCPPIPEDIR_Templates=/work/HCPpipelines_shang/HCPpipelines/global/templates \
--env HCPPIPEDIR_Config=/work/HCPpipelines_shang/HCPpipelines/global/config \
--env CARET7DIR=/app/.pixi/envs/fmriprep/bin \
--env FSLDIR=/app/.pixi/envs/fmriprep \
--env MSMBINDIR=/usr/local/bin \
--env MSMCONFIGDIR=/work/HCPpipelines_shang/HCPpipelines/MSMConfig \
--bind /scratch/users/k20009014:/work \
/scratch/users/k20009014/fmriprep_latest.sif \
bash -c "

# Exit immediately if a command fails or an undefined variable is used.
set -eu

# Subject identifier passed in from the SLURM array task.
Subject=${SUBJECT}

# Root directory containing the outputs from the preceding structural stages.
StudyFolder=/work/derivatives_batch

# Record the current subject in the SLURM output log.
echo Subject: \${Subject}


# -------------------------------------------------------------------------
# Run PostFreeSurferPipeline.sh
# -------------------------------------------------------------------------

# The pipeline:
# - converts FreeSurfer surfaces into HCP-compatible surface spaces;
# - creates standard high- and low-resolution meshes;
# - maps cortical and subcortical labels;
# - performs MSMSulc surface registration;
# - prepares 2 mm grayordinate outputs for subsequent functional processing.
\${HCPPIPEDIR}/PostFreeSurfer/PostFreeSurferPipeline.sh \
  --study-folder=\${StudyFolder} \
  --subject=\${Subject} \
  --surfatlasdir=\${HCPPIPEDIR_Templates}/standard_mesh_atlases \
  --grayordinatesdir=\${HCPPIPEDIR_Templates}/91282_Greyordinates \
  --grayordinatesres=2 \
  --hiresmesh=164 \
  --lowresmesh=32 \
  --subcortgraylabels=\${HCPPIPEDIR_Config}/FreeSurferSubcorticalLabelTableLut.txt \
  --freesurferlabels=\${HCPPIPEDIR_Config}/FreeSurferAllLut.txt \
  --refmyelinmaps=\${HCPPIPEDIR_Templates}/standard_mesh_atlases/Conte69.MyelinMap_BC.164k_fs_LR.dscalar.nii \
  --regname=MSMSulc \
  --processing-mode=LegacyStyleData
"
