#!/bin/bash

# =============================================================================
# HCP fMRIVolume pipeline: SLURM array job
#
# Purpose:
# Run the HCP volumetric fMRI preprocessing pipeline for each subject in a SLURM array. 
# Each subject is processed across two resting-state and two cartoon fMRI runs using the structural outputs generated by the previous HCP preprocessing stages.
#
# Inputs:
# - Subject list (subjects_ses01.txt)
# - Raw functional BOLD images
# - Structural HCP derivatives
#
# Outputs:
# - Volumetric fMRI preprocessing results written to the derivatives folder.
# =============================================================================

#SBATCH --job-name=fMRIVol_batch
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=16:00:00
#SBATCH --array=1-12

# %A is the parent job ID and %a is the array-task ID.
#SBATCH --output=/scratch/users/k20009014/logs/fMRIVol_%A_%a.out
#SBATCH --error=/scratch/users/k20009014/logs/fMRIVol_%A_%a.err


# Read the subject corresponding to the current SLURM array task.
SUBJECT=$(sed -n "${SLURM_ARRAY_TASK_ID}p" /scratch/users/k20009014/subjects_ses01.txt)


# Launch the HCP Pipelines container with the required environment variables and mounted directories.
singularity exec \
--env FS_LICENSE=/work/license.txt \
--env HCPPIPEDIR=/work/HCPpipelines_shang/HCPpipelines \
--env HCPPIPEDIR_Global=/work/HCPpipelines_shang/HCPpipelines/global \
--env HCPPIPEDIR_Templates=/work/HCPpipelines_shang/HCPpipelines/global/templates \
--env HCPPIPEDIR_Config=/work/HCPpipelines_shang/HCPpipelines/global/config \
--env CARET7DIR=/opt/workbench/bin_linux64 \
--bind /scratch/users/k20009014:/work \
--bind /scratch/prj/cortical_imaging_biobank/GSW/ADULT:/data \
/scratch/users/k20009014/hcppipelines_latest.sif \
bash -c "


# Stop if a command fails or an undefined variable is used.
set -eu

Subject=${SUBJECT}
StudyFolder=/work/derivatives_batch


# Support both possible dataset directory structures.
if [ -d /data/\${Subject}/ses-01 ]; then
  Base=/data/\${Subject}/ses-01
else
  Base=/data/\${Subject}
fi


# Functional runs to process for each subject.
Runs=(
  task-rest_run-01
  task-rest_run-02
  task-cartoon_run-01
  task-cartoon_run-02
)


# Process each functional run sequentially.
for RunName in \${Runs[@]}; do
    # Construct the path to the input BOLD image.
  fMRITimeSeries=\${Base}/func/\${Subject}_ses-01_\${RunName}_bold.nii

  echo Processing \${Subject} \${RunName}
  echo Input: \${fMRITimeSeries}

  \  # Run the HCP volumetric fMRI preprocessing pipeline.
  # MCFLIRT is used for motion correction and processing is performed
  # at 2 mm resolution in LegacyStyleData mode.
  ${HCPPIPEDIR}/fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh \
    --studyfolder=\${StudyFolder} \
    --session=\${Subject} \
    --fmritcs=\${fMRITimeSeries} \
    --fmriname=\${RunName} \
    --fmrires=2 \
    --biascorrection=LEGACY \
    --fmriscout=NONE \
    --mctype=MCFLIRT \
    --gdcoeffs=NONE \
    --dcmethod=NONE \
    --dof=6 \
    --processing-mode=LegacyStyleData \
    --wb-resample=TRUE \
    --matlab-run-mode=2
done
"
