#!/bin/bash

# =============================================================================
# HCP fMRISurface pipeline: SLURM array job
# =============================================================================
#
# Purpose
# -------
# Run the HCP surface-based fMRI processing stage for multiple subjects using a SLURM job array.
#
# For each subject, this script processes two resting-state and two cartoon fMRI runs. 
# The pipeline maps the volumetric fMRI data generated by the preceding fMRIVolume stage onto the cortical surface and produces grayordinate-format outputs.
#
# Inputs
# ------
# - Subject list:
#     /scratch/users/k20009014/subjects_ses01.txt
# - Volumetric fMRI outputs from the preceding HCP fMRIVolume stage
# - Structural and surface derivatives generated by the HCP structural stages
# - HCP Pipelines container:
#     /scratch/users/k20009014/hcppipelines_latest.sif
#
# Outputs
# -------
# Surface-based fMRI and grayordinate outputs are written under:
#     /scratch/users/k20009014/derivatives_batch/
#
# SLURM standard-output and error logs are written under:
#     /scratch/users/k20009014/logs/
#
# Notes
# -----
# - One SLURM array task processes one subject.
# - Four functional runs are processed sequentially for each subject.
# - Surface registration uses MSMSulc.
# - Outputs are generated using a 32k low-resolution mesh and 2 mm grayordinate resolution.
# =============================================================================


# -------------------------------------------------------------------------
# SLURM resource requests and logging
# -------------------------------------------------------------------------

#SBATCH --job-name=fMRISurf_batch
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=8
#SBATCH --mem=32G
#SBATCH --time=12:00:00
#SBATCH --array=1-12

# %A is the parent SLURM job ID and %a is the array-task ID.
#SBATCH --output=/scratch/users/k20009014/logs/fMRISurf_%A_%a.out
#SBATCH --error=/scratch/users/k20009014/logs/fMRISurf_%A_%a.err


# -------------------------------------------------------------------------
# Select the subject assigned to the current array task
# -------------------------------------------------------------------------

# Read the line corresponding to SLURM_ARRAY_TASK_ID from the subject list.
SUBJECT=$(sed -n "${SLURM_ARRAY_TASK_ID}p" /scratch/users/k20009014/subjects_ses01.txt)


# -------------------------------------------------------------------------
# Execute the fMRISurface pipeline inside the HCP container
# -------------------------------------------------------------------------

# Environment variables define the FreeSurfer licence, HCP Pipelines paths
# and Connectome Workbench location. The user's scratch directory is mounted
# inside the container as /work.
singularity exec \
--env FS_LICENSE=/work/license.txt \
--env HCPPIPEDIR=/work/HCPpipelines_shang/HCPpipelines \
--env HCPPIPEDIR_Global=/work/HCPpipelines_shang/HCPpipelines/global \
--env HCPPIPEDIR_Templates=/work/HCPpipelines_shang/HCPpipelines/global/templates \
--env HCPPIPEDIR_Config=/work/HCPpipelines_shang/HCPpipelines/global/config \
--env CARET7DIR=/opt/workbench/bin_linux64 \
--bind /scratch/users/k20009014:/work \
/scratch/users/k20009014/hcppipelines_latest.sif \
bash -c "

# Exit immediately if a command fails or an undefined variable is used.
set -eu

# Subject identifier passed from the SLURM array task.
Subject=${SUBJECT}

# Root directory containing the HCP derivatives.
StudyFolder=/work/derivatives_batch


# -------------------------------------------------------------------------
# Define the functional runs to process
# -------------------------------------------------------------------------

Runs=(
  task-rest_run-01
  task-rest_run-02
  task-cartoon_run-01
  task-cartoon_run-02
)


# -------------------------------------------------------------------------
# Run surface processing for each functional run
# -------------------------------------------------------------------------

for RunName in \${Runs[@]}; do
  # Record the current subject and run in the SLURM output log.
  echo Processing surface for \${Subject} \${RunName}

  # Map the preprocessed volumetric fMRI data onto the cortical surface and
  # create grayordinate outputs.
  #
  # Key settings:
  # - 32k low-resolution cortical mesh
  # - 2 mm fMRI and grayordinate resolution
  # - 2 mm FWHM surface smoothing
  # - MSMSulc surface registration
  # - fMRI quality-control output enabled
  # - good-voxel processing enabled
  \${HCPPIPEDIR}/fMRISurface/GenericfMRISurfaceProcessingPipeline.sh \
    --studyfolder=\${StudyFolder} \
    --session=\${Subject} \
    --fmriname=\${RunName} \
    --lowresmesh=32 \
    --fmrires=2 \
    --smoothingFWHM=2 \
    --grayordinatesres=2 \
    --regname=MSMSulc \
    --fmri-qc=YES \
    --goodvoxel=YES
done
"
